# Generated by Django 3.2.4 on 2021-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleml', '0004_auto_20210628_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemodel',
            old_name='category_id',
            new_name='category',
        ),
    ]
