# Generated by Django 3.2.4 on 2021-07-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleml', '0005_rename_category_id_telemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teleml.category'),
        ),
    ]
